#!/usr/bin/make
# SCE CONFIDENTIAL
# PlayStation(R)3 Programmer Tool Runtime Library 475.001
#                 Copyright (C) 2007 Sony Computer Entertainment Inc.
#                                                All Rights Reserved.

include MakeDefs

SUBDIRS = \
	Tutorial/1_BasicCg


include MakeRules
